version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: go-bloggie
    env_file:
      - .env
    ports:
      - 8080:${APP_PORT}
    volumes:
      - .:/app
    command: CompileDaemon -polling -build="go build -buildvcs=false -o app/bin/bloggie cmd/server/main.go" -command="./app/bin/bloggie"